name = "log-share-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "LOG_SHARE"
id = "YOUR_KV_ID"

[env.production]
kv_namespaces = [
  { binding = "LOG_SHARE", id = "YOUR_KV_ID" }
]
